#!/usr/bin/env python3
"""Regenerate ../icons.css from the icons in this directory.

Tern plugin stylesheets can't load local image files and ignore SVG masks, but
they render data URIs as background images. Colours can't come from CSS
variables inside a data URI, so each icon is painted with its brand's own
colours, picked per appearance with light-dark().

Octicons: https://github.com/primer/octicons (MIT, see LICENSE). linear.svg is
Linear's official logo mark from its brand assets. Run after replacing an icon:
python3 icons/generate-css.py
"""
from pathlib import Path
from urllib.parse import quote

HERE = Path(__file__).resolve().parent
# (selector, icon, light colour, dark colour).
ICONS = [
    # Pull request states, in GitHub Primer colours.
    ("[data-role='overseer.prDraft']", "git-pull-request-draft-16.svg", "#59636e", "#9198a1"),
    ("[data-role='overseer.prOpen']", "git-pull-request-16.svg", "#1a7f37", "#3fb950"),
    ("[data-role='overseer.prMerged']", "git-merge-16.svg", "#8250df", "#ab7df8"),
    ("[data-role='overseer.prClosed']", "git-pull-request-closed-16.svg", "#d1242f", "#f85149"),
    # Linear ticket link: Linear's dark mark on light, light mark on dark.
    ("[data-role='overseer.linear']", "linear.svg", "#222326", "#ffffff"),
    # Help button beside the Projects heading: muted, accent blue on hover/focus.
    ("[data-role='overseer.infoButton']", "info-16.svg", "#59636e", "#9198a1"),
    ("[data-role='overseer.infoButton']:hover,\n[data-role='overseer.infoButton']:focus-visible",
     "info-16.svg", "#0969da", "#4493f8"),
]


def data_uri(svg: str, colour: str) -> str:
    painted = svg.replace("<svg ", f'<svg fill="{colour}" ', 1)
    return f'url("data:image/svg+xml;utf8,{quote(painted)}")'


def main() -> None:
    rules = ["/* Generated by icons/generate-css.py from Primer Octicons (MIT) and Linear's logo. Do not edit. */"]
    for selector, name, light, dark in ICONS:
        svg = (HERE / name).read_text().strip()
        rules.append(
            f"{selector} {{\n"
            f"  /* icons/{name} */\n"
            f"  background-image: light-dark({data_uri(svg, light)}, {data_uri(svg, dark)});\n"
            "}"
        )
    (HERE.parent / "icons.css").write_text("\n".join(rules) + "\n")


if __name__ == "__main__":
    main()
